version: '3'

services:
  magic-platform:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: mlops
        MAGE_CODE_PATH: /home/src
    environment:
      - MAGE_CODE_PATH=/home/src
      - PROJECT_NAME=mlops
      - PYTHONPATH=/home/src/mlops
    volumes:
      - .:/home/src
    ports:
      - "6789:6789"
    networks:
      - app-network
    depends_on:
      - magic-database

  magic-database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mage
      POSTGRES_USER: magic
      POSTGRES_PASSWORD: magic
    ports:
      - "5432:5432"
    networks:
      - app-network

  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./mlflow_data:/home/mlflow_data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge